-- ============================================
-- Question Bank Seed Data (Turkish)
-- 200 Relationship Questions for Daily Prompts
-- ============================================

INSERT INTO public.questions (text, tags, relationship_types, difficulty) VALUES

-- ============================================
-- QUESTIONS 1-50
-- ============================================
('Bugün seninle ilgili minnettar olduğum, fark ettiğin ya da etmediğin o küçük detay nedir?', ARRAY['takdir', 'şükran', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte geçirdiğimiz tüm zamanlar içinde, ''İyi ki buradayız'' dediğin en unutulmaz an hangisiydi?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Zor bir durumla karşılaştığında senin hangi özelliğine gizlice hayranlık duyuyorum?', ARRAY['hayranlık', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Önümüzdeki 1 yıl içinde sadece ikimizin olduğu hangi macerayı yaşamak beni çok heyecanlandırıyor?', ARRAY['gelecek', 'hayaller', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Bugün sana olan sevgimi en çok hangi küçük hareketimle hissettirebilirim?', ARRAY['sevgi-dilleri', 'ilgi-odaklı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Sence ''biz'' olduğumuzda ortaya çıkan ve dünyadaki başka kimsede olmayan en karakteristik özelliğimiz ne?', ARRAY['biz-olmak', 'bağ-kurucu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Sesini duyduğumda veya eve geldiğini bildiğimde içimde uyanan o en baskın duygu nedir?', ARRAY['pozitif-duygular', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seninle tanıştığımdan beri, senin sayende kendimde fark ettiğim en güzel değişim nedir?', ARRAY['kişisel-gelişim', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Sadece bizim anladığımız ve her seferinde beni güldüren o ''iç şakamız'' nedir?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Kendimi biraz yorgun veya stresli hissettiğimde, senin hangi tavrın bana en büyük sığınak oluyor?', ARRAY['güven', 'huzur', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Bugün yaptığın hangi küçük şey beni gizlice gülümsetti?', ARRAY['takdir', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Seninle ilk tanıştığım gün, üzerindeki kıyafet veya tavrınla ilgili hatırladığım ilk detay ne?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Emekli olduğumuzda, bir sabah uyandığımızda penceremizden ne görmeyi hayal ediyorsun?', ARRAY['gelecek', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Arkadaş ortamındayken senin hangi özelliğinle içten içe gurur duyuyorum?', ARRAY['hayranlık', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Eğer bir film karakteri olsaydın, seni hangi kahramanla özdeşleştirirdim?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Sana sarıldığımda hissettiğim o benzersiz ''ev'' hissini nasıl tarif edebilirim?', ARRAY['derin-bağ', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('En çok hangi konuda bana verdiğin desteği asla unutamam?', ARRAY['takdir', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Mutfakta bir şeyler hazırlarken seni izlemek neden hoşuma gidiyor?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Ölmeden önce yapılacaklar listemizde (bucket list) sadece ikimizin olduğu o ilk madde ne?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birlikte en çok güldüğümüz ve karnımızın ağrıdığı o anı hatırlıyor musun?', ARRAY['anılar', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin zekanın veya mantığının beni en çok etkilediği an hangisiydi?', ARRAY['hayranlık', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Yorgun olduğumda beni dinlendiren o özel davranışın nedir?', ARRAY['takdir', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Eğer ikimiz bir müzik grubu olsaydık, grubumuzun adı ve tarzı ne olurdu?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Seninle ilgili öğrendiğim ve ''İşte benim ruh eşim'' dediğim o ilk bilgi neydi?', ARRAY['derin-bağ', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Hangi parfümün veya kokun bende her zaman ''mutluluk'' duygusunu tetikliyor?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birlikte yaşlanırken, 80 yaşımızda el ele yürürken birbirimize ne fısıldayacağız?', ARRAY['gelecek', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Senin hayata karşı duruşunda en çok hangi ''cesur'' yanını örnek alıyorum?', ARRAY['hayranlık', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('İlk el ele tutuştuğumuz andaki o heyecanı 1-10 arası puanlasak, senin için kaçtı?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Evimizin ruhunu oluşturan, senin kattığın o en güzel dokunuş nedir?', ARRAY['takdir', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte bir ''kurtarılma'' hikayesi yazsaydık, beni hangi zor durumdan nasıl çekip alırdın?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Kelimeler olmadan, sadece gözlerimize bakarak anlaştığımız o anlardan birini anlatır mısın?', ARRAY['derin-bağ', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Sana özel olan o ''imza'' gülüşünü gördüğümde içimden geçen ilk cümle ne?', ARRAY['küçük-şeyler', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Bu hafta sonu dünyadaki tüm masraflarımız ödenmiş olsa, beni nereye götürürdün?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Hangi başarımı kutlarken verdiğin tepki bana kendimi en değerli hissettiren an oldu?', ARRAY['takdir', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seninle paylaştığım en sessiz ama en huzurlu anımız hangisiydi?', ARRAY['anılar', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Senin nezaketin veya başkalarına olan yardımın beni ne kadar gururlandırıyor biliyor musun?', ARRAY['hayranlık', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Eğer ikimiz bir süper kahraman ikilisi olsaydık, özel güçlerimiz ne olurdu?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Sabah uyandığında yüzünde gördüğüm o ilk ifade neden günümü güzelleştiriyor?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Bana olan güvenini en çok hissettiğim an hangisiydi?', ARRAY['derin-bağ', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte izlediğimiz ve ''bizim filmimiz'' dediğimiz o film hangisi?', ARRAY['anılar', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Bir tartışmayı tatlıya bağlama şeklimizde senin en sevdiğim yanın hangisi?', ARRAY['takdir', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte inşa etmek istediğin o ''hayalindeki ev''in en önemli odası hangisi?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin tutkuyla bağlı olduğun bir şeyi anlatırken gözlerindeki o ışığı neye benzetiyorum?', ARRAY['hayranlık', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Bana gönderdiğin hangi mesajı hala saklıyorum veya defalarca okudum?', ARRAY['küçük-şeyler', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Kendi özel dilimizde sadece ikimizin bildiği 3 kelime nedir?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin yanındayken dünyanın geri kalanını unuttuğum o anları nasıl başarıyorsun?', ARRAY['derin-bağ', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte yaptığımız en ''çılgın'' veya plansız yolculuk hangisiydi?', ARRAY['anılar', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Benim en sevmediğim özelliğimi bile nasıl sevgiyle kabul edebiliyorsun?', ARRAY['takdir', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Bir sonraki doğum gününde sana hangi duyguyu hediye etmemi istersin?', ARRAY['gelecek', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Senin sabrının benim hayatımı nasıl kolaylaştırdığını farkında mısın?', ARRAY['hayranlık', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),

-- ============================================
-- QUESTIONS 51-100
-- ============================================
('Bana sarıldığında gelen o kendine has kokuyu başka neyle kıyaslayabilirim?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Seninle geçirdiğimiz ilk tatilin en komik olayı neydi?', ARRAY['anılar', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Seni düşünürken arka planda hangi şarkı çalıyor?', ARRAY['derin-bağ', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Senin yanındayken kendimi neden daha ''cesur'' hissediyorum?', ARRAY['takdir', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Beş yıl sonraki ''biz''e bugün bir not bıraksan ne yazardın?', ARRAY['gelecek', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Partnerinin ''gizli yeteneği'' nedir ve bu seni neden gülümsetiyor?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin en çok hangi ''çocuksu'' yanını seviyorum?', ARRAY['hayranlık', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Yağmurlu bir günde sadece ikimizin olduğu en güzel an hangisiydi?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Gözlerinin içine baktığımda orada gördüğüm ''gelecek'' resmi nasıl?', ARRAY['derin-bağ', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('İşten eve geldiğimde beni karşılayışın neden tüm yorgunluğumu alıyor?', ARRAY['takdir', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Benim hakkımda sadece senin bildiğin o ''sevimli'' alışkanlığım nedir?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birlikte öğrenmek istediğin o yeni hobi veya beceri nedir?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Zor zamanlarımda bana ''ışık'' olan o cümlen hangisiydi?', ARRAY['hayranlık', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Eğer bir hayvan olsaydık, hangi hayvan ikilisi bizim uyumumuzu anlatırdı?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('İlk buluşmamızda kalbinin en hızlı attığı o an hangisiydi?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birbirimizin cümlesini tamamladığımız o anlarda ne hissediyorsun?', ARRAY['derin-bağ', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Senin sayende hayatıma giren en güzel alışkanlık nedir?', ARRAY['takdir', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Yaşlandığımızda sallanan sandalyelerimizde otururken ne hakkında konuşacağız?', ARRAY['gelecek', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Senin dürüstlüğüne neden bu kadar çok hayranım?', ARRAY['hayranlık', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin elini tuttuğunda hissettiğin o güven duygusunu nasıl tarif edersin?', ARRAY['küçük-şeyler', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte yediğimiz en basit ama en lezzetli yemek hangisiydi?', ARRAY['anılar', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Bir günlüğüne bedenlerimizi değiştirsek, senin bedeninde yapacağım ilk şey ne olurdu?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Ruhunun en çok hangi rengi yansıttığını düşünüyorum?', ARRAY['derin-bağ', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Beni en çok hangi konuda motive etmen hayatımı değiştirdi?', ARRAY['takdir', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seninle hangi şehirde kaybolmayı hayal ediyorum?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin merhametinin sınırlarını gördüğüm o an hangisiydi?', ARRAY['hayranlık', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('En sevdiğin fotoğrafımız hangisi ve neden o?', ARRAY['küçük-şeyler', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Hangi şarkıyı duyduğunda aklına hemen ''biz'' geliyoruz?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Seninleyken ''maskelerimi'' indirmemi sağlayan o şey nedir?', ARRAY['derin-bağ', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Bana olan aşkını en çok hissettiğim ''sıradan'' an hangisiydi?', ARRAY['takdir', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte kuracağımız o büyük hayalin ilk adımı sence ne olmalı?', ARRAY['gelecek', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin en komik uyuma şekli veya sabah hali nedir?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin öğrenmeye olan merakın beni neden bu kadar etkiliyor?', ARRAY['hayranlık', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerine bir madalya verecek olsan, hangi dalda ''Dünya Şampiyonu'' olurdu?', ARRAY['küçük-şeyler', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birlikte kutladığımız en anlamlı özel gün hangisiydi?', ARRAY['anılar', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seninleyken kendimin ''en iyi versiyonu'' olduğumu neden hissediyorum?', ARRAY['derin-bağ', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Partnerinin sana verdiği en iyi tavsiye neydi?', ARRAY['takdir', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte yapacağımız bir sonraki ''ilk'' ne olacak?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin estetik bakış açını veya zevklerini neden çok beğeniyorum?', ARRAY['hayranlık', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birlikte hazırladığımız o ''pazar kahvaltıları''nın en sevdiğin yanı nedir?', ARRAY['küçük-şeyler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Seninle ilgili hatırladığım ''en küçük'' ama en tatlı detay nedir?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birbirimizin sessizliğini paylaşabilmek sence neden bu kadar değerli?', ARRAY['derin-bağ', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Partnerinin senin için yaptığı o ''gizli kahramanlık'' neydi?', ARRAY['takdir', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinle yaşlanmanın en güzel tarafı sence ne olacak?', ARRAY['gelecek', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Eğer bir masalın içinde olsaydık, bizim sonumuz nasıl biterdi?', ARRAY['eğlence', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin başkalarına verdiğin değer neden benim kalbimi eritiyor?', ARRAY['hayranlık', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin sana bakarken kullandığı o ''özel bakışı'' nasıl tanımlarsın?', ARRAY['küçük-şeyler', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinle paylaştığın en heyecan verici ''başarı'' anı hangisiydi?', ARRAY['anılar', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Senin yanındayken zamanın nasıl geçtiğini neden anlamıyorum?', ARRAY['derin-bağ', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Bugün partnerine ''Seni seviyorum'' demek için en güzel sebebin ne?', ARRAY['sonsuzluk', 'aşk'], ARRAY['dating', 'married', 'long-distance'], 'easy'),

-- ============================================
-- QUESTIONS 101-150
-- ============================================
('Sadece ikimize özel olan ve her yıl mutlaka yapmalıyız dediğin o ''küçük gelenek'' nedir?', ARRAY['gelenekler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Kalabalık bir ortamda göz göze geldiğimizde bana fısıldadığın o gizli bakışın anlamı sence ne?', ARRAY['sosyal-dünya', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seninle tanışana kadar fark etmediğim ama senin sayende sevdiğim bir özelliğim var mı?', ARRAY['kişisel-keşif', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Bir adaya düşsek ve yanımıza sadece 3 ortak anımızı alma şansımız olsa, hangi 3 kareyi seçerdin?', ARRAY['hayali-senaryo', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Bugün senin için yapabileceğim, modunu anında yükseltecek o ''küçük jest'' ne olurdu?', ARRAY['günlük-destek', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin çalışma disiplinin veya bir şeye odaklanma şeklin beni neden bu kadar çok motive ediyor?', ARRAY['ilham', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seninle özdeşleştirdiğim o huzurlu ''ev kokusu'' sence hangi notalardan oluşuyor?', ARRAY['duyusal', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte yaşayacağımız evin bahçesine bir ağaç diksek, bu hangi ağaç olurdu ve neden?', ARRAY['gelecek', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Seninle ilgili en sevdiğim ''garip'' ama bir o kadar tatlı alışkanlığın nedir?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Başkalarına benden bahsederken en çok hangi özelliğimi gururla anlatıyorsun?', ARRAY['takdir', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Üzgün olduğumda sadece elime dokunmanın bana yettiğini nasıl bu kadar iyi biliyorsun?', ARRAY['iletişim', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte ıslanmaktan çekinmediğimiz o yağmurlu günü/anı hatırlıyor musun?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Eğer zaman yolculuğu yapabilseydik, seninle hangi döneme gidip bir gün geçirmek isterdim?', ARRAY['hayali-senaryo', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Mutfakta beraber bir şeyler yaparken senin ''şef'' yardımcın olmak neden çok keyifli?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Sana dair en çok hangi konuda ''asla beni yanıltmaz'' diyorum?', ARRAY['güven', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Her hafta sonu ritüelimiz haline gelmesini istediğin o aktivite ne?', ARRAY['gelenekler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birbirimizin en yakın arkadaşı olmamız, diğer insanlarla olan ilişkilerimizi nasıl güzelleştiriyor?', ARRAY['sosyal-dünya', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Seninle geçirdiğim süre boyunca sabır konusunda senden öğrendiğim en büyük ders ne?', ARRAY['kişisel-keşif', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin en iyi yaptığı ''taklit'' veya komik hareket hangisi?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Sadece gözlerimize bakarak anlaştığımız o sessiz dilimizi neye borçluyuz?', ARRAY['derin-bağ', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte yaşlanırken en çok hangi hobiyi beraber sürdürmeyi hayal ediyorsun?', ARRAY['gelecek', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Benim en ufak bir başarımı bile nasıl dev bir kutlamaya çevirebiliyorsun?', ARRAY['takdir', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Hangi şarkı çaldığında sanki zaman duruyor ve sadece biz kalıyoruz?', ARRAY['duyusal', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Sabahları uykulu halinle bana bakışın neden günün en güzel anı?', ARRAY['küçük-şeyler', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('İkimiz bir roman yazsaydık, kitabın adı ve son cümlesi ne olurdu?', ARRAY['hayali-senaryo', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Partnerinin senin üzerindeki ''sakinleştirici'' etkisini nasıl tarif edersin?', ARRAY['kişisel-keşif', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte izlediğimiz ilk gün batımında ne hissettiğini hatırlıyor musun?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Hayata karşı pozitif kalmanı sağlayan o içindeki güce nasıl hayran olmayayım?', ARRAY['ilham', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('İşlerin yoğun olduğu bir günde sana atacağım hangi emoji seni gülümsetir?', ARRAY['günlük-destek', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Tatillerde mutlaka yapmalıyız dediğimiz o bize özel ''ritüel'' nedir?', ARRAY['gelenekler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Yeni bir ortama girdiğimizde birbirimizi nasıl tamamladığımızı fark ediyor musun?', ARRAY['sosyal-dünya', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Ruhunun en derinlerinde sadece benim görebildiğim o ''özel oda''da ne var?', ARRAY['derin-bağ', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikteyken yaptığımız en saçma ama en eğlenceli şey neydi?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Zor bir karar verirken senin fikrini almanın bana verdiği o büyük güven hissi...', ARRAY['takdir', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('10 yıl sonraki halimize tek kelimelik bir tavsiye versen bu ne olurdu?', ARRAY['gelecek', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Partnerinin ses tonundaki hangi vurgu sana huzur veriyor?', ARRAY['duyusal', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Televizyon izlerken birbirimize yaslanış şeklimizin neden bir dili var?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Eğer bir sihirli değneğin olsa, bizim için hangi ''an''ı sonsuza kadar dondururdun?', ARRAY['hayali-senaryo', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin yanında en çok hangi konuda ''kendin gibi'' hissediyorsun?', ARRAY['kişisel-keşif', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte yürüdüğümüz o en uzun yolun hikayesi neydi?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Senin nezaketinin, kaba bir dünyada bana nasıl nefes aldırdığını biliyor musun?', ARRAY['ilham', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Her pazar akşamı birbirimize söyleyeceğimiz o ''iyi ki'' cümlesi ne olsun?', ARRAY['gelenekler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Arkadaşlarımızla olduğumuzda ''biz'' olmanın en sevdiğin yanı nedir?', ARRAY['sosyal-dünya', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Kalbinin ritmini sadece sarılarak hissetmek sence neden mucizevi?', ARRAY['derin-bağ', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Sadece ikimizin olduğu bir ''gizli kulüp'' kurmuş olsak, kulübün şifresi ne olurdu?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Hangi küçük sakarlığımda bile bana olan sevginle gülümsüyorsun?', ARRAY['takdir', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Beraber çıkacağımız ilk uzun yolculuğun şarkı listesinde ilk sırada ne var?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Partnerinin elini tuttuğunda parmak uçlarından kalbine akan o his...', ARRAY['duyusal', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Bana aldığın o en küçük ama en anlamlı hediye neydi ve neden onu saklıyorum?', ARRAY['küçük-şeyler', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Eğer ikimiz birer yıldız olsaydık, gökyüzünde hangi takımyıldızını oluştururduk?', ARRAY['hayali-senaryo', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),

-- ============================================
-- QUESTIONS 151-200
-- ============================================
('Seninleyken ''hayır'' demeyi veya sınırlarımı çizmeyi nasıl daha iyi öğrendim?', ARRAY['kişisel-keşif', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte kaybolduğumuz ama sonunda çok güzel bir yer bulduğumuz o anı hatırlıyor musun?', ARRAY['anılar', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin bir şeyi tutkuyla savunman neden benim sana tekrar aşık olmamı sağlıyor?', ARRAY['ilham', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Mevsim geçişlerinde (örneğin ilkbahar geldiğinde) beraber yapacağımız ilk şey ne?', ARRAY['gelenekler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Ailemizle bir araya geldiğimizde ''bizim'' duruşumuzun en sevdiğin tarafı ne?', ARRAY['sosyal-dünya', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seninleyken dünyanın gürültüsünü nasıl bu kadar kolay kısabiliyorum?', ARRAY['derin-bağ', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('İkimiz birer emoji olsaydık, yan yana gelince nasıl görünürdük?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('En kararsız olduğum anda senin ''buradayım'' demen neden her şeyi çözüyor?', ARRAY['takdir', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Hayalimizdeki bahçede hangi meyveleri beraber toplayacağız?', ARRAY['gelecek', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Partnerinin sana bakarken gözlerinin kenarında oluşan o çizgileri seviyor musun?', ARRAY['duyusal', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Evde sıradan bir akşamda seninle aynı kitabı okumak veya film izlemek neden özel?', ARRAY['küçük-şeyler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Eğer dünyadaki tüm dilleri bilseydik, birbirimize hangi dilde ''seni seviyorum'' derdik?', ARRAY['hayali-senaryo', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Senin sayende daha önce hiç denemediğim hangi yemeği veya aktiviteyi sevdim?', ARRAY['kişisel-keşif', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Partnerinin sana yaptığı en beklenmedik ve tatlı sürpriz neydi?', ARRAY['anılar', 'nostaljik'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Senin zorluklar karşısındaki o ''yıkılmaz'' duruşunu nasıl örnek alıyorum?', ARRAY['ilham', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Her ayın bir gününü ''bizim günümüz'' ilan etsek, o gün ne yapardık?', ARRAY['gelenekler', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Dışarıdaki insanlar bizim en çok hangi özelliğimizi kıskanıyor olabilirler?', ARRAY['sosyal-dünya', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birbirimizin zihnindeki o ''sessiz düşünceleri'' nasıl bu kadar iyi okuyoruz?', ARRAY['derin-bağ', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Eğer ikimiz birer çizgi film karakteri olsaydık, başımızdan geçen en komik macera ne olurdu?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Partnerinin sana verdiği en cesurca destek neydi?', ARRAY['takdir', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte göreceğimiz o ''ilk'' dünya harikası hangisi olmalı?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Onun adını telefonunda gördüğünde kalbinde kıpırdayan o hissi tarif et.', ARRAY['duyusal', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin sana hazırladığı o en basit ''moral tabağı'' (meyve, kahve vb.) neden çok lezzetli?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birlikte bir ''zaman kapsülü'' gömsek, içine bugünden ne koyardık?', ARRAY['hayali-senaryo', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin yanında en çok hangi ''zayıf'' yanını rahatça gösterebiliyorsun?', ARRAY['kişisel-keşif', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Beraber katıldığımız o en eğlenceli düğün veya parti hangisiydi?', ARRAY['anılar', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Onun hayata bakışındaki o ''naiflik'' seni nasıl daha iyi bir insan yapıyor?', ARRAY['ilham', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Yılın ilk karı yağdığında yapacağımız o ritüel ne olsun?', ARRAY['gelenekler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Birbirimize verdiğimiz o ''eve gidelim artık'' gizli işareti nedir?', ARRAY['sosyal-dünya', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Ruhlarımızın birbirine ''dokunduğu'' o en yüksek an hangisiydi?', ARRAY['derin-bağ', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Onun en çok hangi ''yanlış anladığı'' kelimeye veya olaya gülüyoruz?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Partnerinin senin ''sessiz'' çığlıklarını nasıl bu kadar iyi duyduğunu hiç düşündün mü?', ARRAY['takdir', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte yaşayacağımız o evin en çok hangi köşesinde vakit geçireceğiz?', ARRAY['gelecek', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Onun teninin sıcaklığını en çok hangi mevsimde seviyorsun?', ARRAY['duyusal', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Partnerinin sana ayırdığı o son lokma neden dünyanın en büyük aşk ilanı?', ARRAY['küçük-şeyler', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Eğer dünyadaki tüm renkler silinseydi, birbirimizi hangi renkle hatırlardık?', ARRAY['hayali-senaryo', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Partnerinin seni en çok hangi konuda ''şaşırttığını'' hatırlıyorsun?', ARRAY['kişisel-keşif', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Birlikte izlediğimiz o en sıkıcı filmde bile neden çok eğlendik?', ARRAY['anılar', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Onun öğrenme azmi senin içindeki hangi merakı tetikliyor?', ARRAY['ilham', 'güçlendirici'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Her doğum gününde birbirimize yazacağımız o ''mektup'' geleneğine ne dersin?', ARRAY['gelenekler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Bir ortamda partnerinin senin yerini nasıl koruduğunu fark ettiğin o an...', ARRAY['sosyal-dünya', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Seni ''iyileştiren'' o özel kelimesi veya cümlesi nedir?', ARRAY['derin-bağ', 'duygusal'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('İkinizin ortak ''en saçma'' dans figürü nasıl bir şey?', ARRAY['mizah', 'eğlenceli'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Onun senin için yaptığı o ''görünmez'' iyiliklerin ne kadar farkındasın?', ARRAY['takdir', 'tatlı'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Hayalimizdeki o küçük kafe/dükkan/atölye açılsa adı ne olurdu?', ARRAY['gelecek', 'heyecan-verici'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Onun gülümsemesini bir doğa olayına benzetsen bu ne olurdu?', ARRAY['duyusal', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Yorgun olduğunda partnerinin başını omzuna koyması neden dünyanın en güvenli yeri?', ARRAY['küçük-şeyler', 'huzurlu'], ARRAY['dating', 'married', 'long-distance'], 'easy'),
('Eğer birbirimizi başka bir hayatta bulsaydık, sence yine aynı şekilde mi aşık olurduk?', ARRAY['hayali-senaryo', 'derin'], ARRAY['dating', 'married', 'long-distance'], 'deep'),
('Birlikte paylaştığımız ''en sessiz'' ama ''en çok şey anlatan'' fotoğrafımız hangisi?', ARRAY['anılar', 'romantik'], ARRAY['dating', 'married', 'long-distance'], 'medium'),
('Şu an partnerinin gözlerinin içine baksan, ona kelimesiz ne söylerdin?', ARRAY['sonsuzluk', 'aşk'], ARRAY['dating', 'married', 'long-distance'], 'deep');

-- Grant permissions for the questions table
GRANT SELECT ON public.questions TO authenticated;
